name: Code Quality

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@v3.90.8
    
    - name: Install uv
      uses: astral-sh/setup-uv@v7.0.0
      with:
        version: "latest"

    - name: Install ruff
      run: uv tool install ruff

    - name: Submit uv dependency snapshot
      uses: rmuir/uv-dependency-submission@e021503b1390bff207cc96b4da354b1091607b9e # v1.0.0

    - name: Run ruff check
      run: uv tool run ruff check --output-format=github .

    - name: Run ruff format check
      run: uv tool run ruff format --check .
